objtool: fix build of 64-bit kernel with 32-bit userspace
This patch fixes building of 64-bit kernel on 32-bit userspace (I tested
it on RHEL-6-i686 and Debian-Sid-x32).

There are still some more bugs - when building 64-bit kernel on 32-bit
Debian 7 distribution, objtool corrupts object files so that the linker
doesn't recognize them (ld doesn't recognize the format of the file at all
and gold prints a lot of errors).

Another problem - when building 32-bit kernel, why do you force frame
pointers on and why did you hide CONFIG_GUESS_UNWINDER behind
CONFIG_EXPERT? Frame pointers increase code size and register pressure,
most users don't need precise stacktraces, so CONFIG_GUESS_UNWINDER should
be default for non-expert users just like it was before.

Is there some technical reason why do you want to avoid
CONFIG_GUESS_UNWINDER?

From: Mikulas Patocka <mpatocka@redhat.com>
Subject: [PATCH] objtool: fix build of 64-bit kernel with 32-bit userspace

The new orc unwinder breaks building 64-bit kernel with 32-bit userspace.
Building the kernel with i386 or x32 userspace fails with this error:

  CC       /usr/src/git/linux-2.6/tools/objtool/orc_dump.o
orc_dump.c: In function 'orc_dump':
orc_dump.c:105:26: error: passing argument 2 of 'elf_getshdrnum' from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (elf_getshdrnum(elf, &nr_sections)) {
                          ^
In file included from /usr/local/include/gelf.h:32:0,
                 from elf.h:22,
                 from warn.h:26,
                 from orc_dump.c:20:
/usr/local/include/libelf.h:304:12: note: expected 'size_t * {aka unsigned int *}' but argument is of type 'long unsigned int *'
 extern int elf_getshdrnum (Elf *__elf, size_t *__dst);
            ^~~~~~~~~~~~~~
orc_dump.c:190:17: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'Elf64_Sxword {aka long long int}' [-Werror=format=]
    printf("%s+%lx:", name, rela.r_addend);
               ~~^          ~~~~~~~~~~~~~
               %llx
cc1: all warnings being treated as errors

This patch fixes the build failure.

Another problem is that if the user specifies HOSTCC or HOSTLD variables,
they are ignored in the makefile tools/objtool/Makefile. This patch
changes the makefile so that it respects these variables.

Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
Signed-off-by: youling257 <youling257@gmail.com>