UPSTREAM: drm/i915: Avoid pointer arithmetic in calculating plane surface offset
VMA offsets are 64 bits. Plane surface offsets are in ggtt and
the hardware register to set this is thus 32 bits. Be explicit
about these and convert carefully to from vma to final size.

This will make sparse happy by not creating 32bit pointers out
of 64bit vma offsets.

Cc: Tvrtko Ursulin <tvrtko.ursulin@intel.com>
Signed-off-by: Mika Kuoppala <mika.kuoppala@intel.com>
Link: http://patchwork.freedesktop.org/patch/msgid/1446204375-29831-1-git-send-email-mika.kuoppala@intel.com
Reviewed-by: Tvrtko Ursulin <tvrtko.ursulin@intel.com>
Signed-off-by: Ville Syrjl <ville.syrjala@linux.intel.com>
(cherry picked from commit 44eb0cb9620c6a53ec8e7073262e2af8079b727f)

BUG=none
TEST=build on x86 (32-bit)

[Seeing errors like this:
/mnt/host/source/src/third_party/kernel/v4.4/drivers/gpu/drm/i915/intel_display.c: In function 'intel_plane_obj_offset':
/mnt/host/source/src/third_party/kernel/v4.4/drivers/gpu/drm/i915/intel_display.c:2969:11: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   offset = (unsigned char *)vma->node.start;
            ^
]

Change-Id: Id8b96a0bf384e25c2250d4c391d49d8e7488095c
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/339654
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>