ANDROID: fs: Export d_absolute_path
The 0-day build bot reports the following build error, seen if SDCARD_FS
is built as module.

ERROR: "d_absolute_path" undefined!

Fixes: 84a1b7d3d312 ("Included sdcardfs source code for kernel 3.0")
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from https://android.googlesource.com/kernel/common android-4.4
 commit cdaa7dcb05f7955e855fa816c21c3210088ca2b8)

BUG=chromium:612862
TEST=build and boot on a few devices

Change-Id: I23236a22fe92a21c1f640ffa5dac29150e0c7766
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/345862
Reviewed-by: Guenter Roeck <groeck@chromium.org>