CHROMIUM: drm/evdi: Fix build error due to bad indentation
0day reports:

drivers/gpu/drm/evdi/evdi_modeset.c: In function 'evdi_crtc_cursor_move':
drivers/gpu/drm/evdi/evdi_modeset.c:242:2: error:
	this 'if' clause does not guard...

BUG=chromium:627639
TEST=Build with -Werror=misleading-indentation

Change-Id: Ibe0df9cb3aea351e69945b98c20c3cd2e2476070
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/389771
Reviewed-by: Bernie Thompson <bhthompson@chromium.org>