UPSTREAM: regulator: mt6311: MT6311_REGULATOR needs to select REGMAP_I2C
This patch fix the below build error:
drivers/regulator/mt6311-regulator.c:111: undefined reference to `__devm_regmap_init_i2c'

Signed-off-by: Henry Chen <henryc.chen@mediatek.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
Cc: stable@vger.kernel.org
(cherry picked from commit aab3c3f34cc2dd8230052770712606d65de6538f
 git://git.kernel.org/pub/scm/linux/kernel/git/broonie/regulator.git fix/mt6311)
Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:38746
TEST=build test chromeos-3.18 & oak-tot

Change-Id: I70d31b23a910a34f275e70706336f730aae41779
Reviewed-on: https://chromium-review.googlesource.com/312916
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>