ANDROID: mm: Export do_munmap
The 0-day build bot reports the following build error, seen if SDCARD_FS
is built as module.

ERROR: "do_munmap" undefined!

Fixes: 84a1b7d3d312 ("Included sdcardfs source code for kernel 3.0")
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from https://android.googlesource.com/kernel/common android-4.4
 commit de679b3bbe8b810b01929b1f27665ede5eb54f37)

BUG=chromium:612862
TEST=build and boot on a few devices

Change-Id: Ifab8f6da895e6c7acedcf3f698c5355021ba3157
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/345865
Reviewed-by: Guenter Roeck <groeck@chromium.org>