UPSTREAM: ASoC: intel: make function stub static
This function stub should have been 'static' in the original patch
so that multiple uses of the header file (in different drivers)
will not cause multiple function definitions.

sound/soc/intel/boards/built-in.o: In function `sst_acpi_find_name_from_hid':
(.text+0x560): multiple definition of `sst_acpi_find_name_from_hid'
sound/soc/intel/atom/built-in.o:(.text+0x10610): first defined here
../scripts/Makefile.build:369: recipe for target 'sound/soc/intel/built-in.o' failed

Fixes: f17131a93f43: add function stub when ACPI is not enabled

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
Link: git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
tag: next-20160531
(cherry picked from commit 2d0b29dca8d6fe49a73cfc16888c1d2e55111d7b)
Signed-off-by: Vedang Patel <vedang.patel@intel.com>

BUG=chrome-os-partner:53967
TEST=with the whole series applied, Audio works on Amenia.

Change-Id: I8d4a97e8c7033eb9c12efa0fb863b1a9b9cd1ab5
Reviewed-on: https://chromium-review.googlesource.com/350451
Commit-Ready: Vedang Patel <vedang.patel@intel.com>
Tested-by: Russ Sage <russ.sage@intel.com>
Reviewed-by: Benson Leung <bleung@chromium.org>