CHROMIUM: ASoC: Intel: common: Add missing include
Compilation fails spitting out the following error:

/mnt/host/source/src/third_party/kernel/v4.4/sound/soc/intel/common/
sst-match-acpi.c:80:16:
error: expected declaration specifiers or '...' before string constant
 MODULE_LICENSE("GPL v2");
                 ^
/mnt/host/source/src/third_party/kernel/v4.4/sound/soc/intel/common/
sst-match-acpi.c:81:20:
error: expected declaration specifiers or '...' before string constant
 MODULE_DESCRIPTION("Intel Common ACPI Match module");

Add the include file to compile successfully.

BUG=chrome-os-partner:53967
TEST=with the whole series applied, Audio works on Amenia.

Change-Id: I0e689dacf664ced28ce307285c57d6fa3363c060
Reviewed-on: https://chromium-review.googlesource.com/347497
Commit-Ready: Vedang Patel <vedang.patel@intel.com>
Tested-by: Russ Sage <russ.sage@intel.com>
Reviewed-by: Benson Leung <bleung@chromium.org>