UPSTREAM: nvmem: Fix build error of missing devm_ioremap_resource on UM
The devres.o gets linked if HAS_IOMEM is present so on ARCH=um
allyesconfig (COMPILE_TEST) failed on many files with:

drivers/built-in.o: In function `mtk_thermal_probe':
mtk_thermal.c:(.text+0x394618): undefined reference to `devm_ioremap_resource'

The users of devm_ioremap_resource() which are compile-testable should
depend on HAS_IOMEM.

BUG=chrome-os-partner:56686
TEST=w/ series can read nvmem

Change-Id: I14784ca0cebcf80be7de22aac41479fd2fe98562
Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit 2ce7aed6a4da8ffa35f0232573a6901c0369720d)
Reviewed-on: https://chromium-review.googlesource.com/379896