UPSTREAM: clk: rockchip: fix coding style for clk-cpu.c
Fix the issue reported by checkpatch:
ERROR: space prohibited before that ',' (ctx:WxW)
+               writel(clksel->val , cpuclk->reg_base + clksel->reg);

BUG=chrome-os-partner:50756
TEST=Build and boot on rk3288

Change-Id: Ieb5e0e6de9ed5dc512d0be432e04b18761fc4cd1
Signed-off-by: Shawn Lin <shawn.lin@rock-chips.com>
Signed-off-by: Heiko Stuebner <heiko@sntech.de>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit fc6d875ecb83cd03afad4486c97a9355e00c8944)