UPSTREAM: ASoC: intel: add function stub when ACPI is not enabled
Add function stub for "sst_acpi_find_name_from_hid()"
when CONFIG_ACPI is not enabled so that the driver will build
successfully. This fixes the following build errors:

(loadable module)
ERROR: "sst_acpi_find_name_from_hid" [sound/soc/intel/boards/snd-soc-sst-bytcr-rt5640.ko] undefined!
(or built-in)
bytcr_rt5640.c:(.text+0x26fc52): undefined reference to `sst_acpi_find_name_from_hid'

Reported-by: Borislav Petkov <bp@alien8.de>
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
Link: git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git
tag: asoc-v4.7
(cherry picked from commit f17131a93f43665a76ae1f6aebdbb3e41674137c)
Signed-off-by: Vedang Patel <vedang.patel@intel.com>

BUG=chrome-os-partner:53967
TEST=with the whole series applied, Audio works on Amenia.

Change-Id: Idf9d982c38cd75fa6262b6f9643dbab1a2be73a9
Reviewed-on: https://chromium-review.googlesource.com/347855
Commit-Ready: Vedang Patel <vedang.patel@intel.com>
Tested-by: Russ Sage <russ.sage@intel.com>
Reviewed-by: Benson Leung <bleung@chromium.org>